export const CONSTANTS = {
    SIGNUP_START: 'SIGNUP_START',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    GET_NEWS_START: 'GET_NEWS_START',
    GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
    GET_NEWS_ERROR: 'GET_NEWS_ERROR',

    ADD_NEWS_START: 'ADD_NEWS_START',
    ADD_NEWS_SUCCESS: 'ADD_NEWS_SUCCESS',
    ADD_NEWS_ERROR: 'ADD_NEWS_ERROR',

    UPDATE_NEWS_START: 'UPDATE_NEWS_START',
    UPDATE_NEWS_SUCCESS: 'UPDATE_NEWS_SUCCESS',
    UPDATE_NEWS_ERROR: 'UPDATE_NEWS_ERROR',

    DELETE_NEWS_START: 'DELETE_NEWS_START',
    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',
    DELETE_NEWS_ERROR: 'DELETE_NEWS_ERROR'
    
}